services:
  ziti-edge-proxy:
    build: .
    ports:
      - "1080:1080"
    environment:
      PROXY_HOST: 0.0.0.0
      PROXY_PORT: 1080
      PROXY_USERNAME: user
      PROXY_PASSWORD: 1234
      ZITI_IDENTITIES: /app/identity.json
    volumes:
      - "./identity.json:/app/identity.json"