services:
  ziti-edge-proxy:
    build: .
    ports:
      - "1080:1080"
      - "8080:8080"
    environment:
      PROXY_HOST: 0.0.0.0
      SOCKS_PORT: 1080
      HTTP_PORT: 8080
      HTTP_ENABLED: true
      SOCKS_ENABLED: false
      PROXY_USERNAME: user
      PROXY_PASSWORD: 1234
      ZITI_IDENTITIES: /app/identity.json
    volumes:
      - "../identity.json:/app/identity.json"