{{- if not .Values.appConfig.identity.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ziti-edge-proxy.secret.identitySecretName" . }}
type: Opaque
data:
  {{- range .Values.appConfig.identity.identities }}
  {{ .name }}.json: "{{ .identity | b64enc }}"
  {{- end }}
{{- end }}
---
{{- if not .Values.appConfig.credential.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ziti-edge-proxy.secret.credentialSecretName" . }}
type: Opaque
data:
  PROXY_USERNAME: "{{ .Values.appConfig.credential.username | b64enc }}"
  PROXY_PASSWORD: "{{ .Values.appConfig.credential.password | default (randAlphaNum 16) | b64enc }}"
{{- end }}