

name: Helm package and push

on:
  push:
    branches:
      - 'main'
      - 'feature/helm-chart'
    paths:
      - 'helm/**'

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Push Helm chart to Github Registry
        uses: bsord/helm-push@4.2.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}
          username: bsord
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: false
          chart-folder: helm